package view;

import classes.Funcionario;
import java.awt.Font;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class CreateUpdateEmployee extends javax.swing.JFrame {

    // FUNCTIONS 
    
    private void setComponentsDefaultValues () {
        
        Font font = new Font("Monospaced", Font.BOLD, 16);
        
        
        
        JLabel[] labels = { 
            labelCity, labelComplement, labelLicenseNumber,
            labelName, labelNumber, labelRole, labelSocialSecurityNumber,
            labelState, labelStreet, labelZipCode
        };
        
        JComponent[] inputs = {
            inputCity, inputComplement, inputLicenseNumber, inputName, inputNumber, 
            comboRole, inputSocialSecurityNumber, inputStreet,
        };
        
        String[] labelsTexts = {
            "* City ", "Complement", "* License Number ", "* Name ", "Number",
            "* Role ", "* SSN ", "* State ", "* Street ", "* Zip Code "
        };
        
        for (int index = 0; index < labels.length; index++) {
            labels[index].setText(labelsTexts[index]);
            labels[index].setFont(font);
        }
        
        this.setTitle("Employee");
        this.setResizable(true);
    }

    public CreateUpdateEmployee() {
        initComponents();
        setComponentsDefaultValues();
        
        comboRole.setSelectedItem("Cargo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        labelSocialSecurityNumber = new javax.swing.JLabel();
        labelRole = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        buttonCreate = new javax.swing.JButton();
        comboRole = new javax.swing.JComboBox<>();
        inputSocialSecurityNumber = new javax.swing.JFormattedTextField();
        addressPanel = new javax.swing.JPanel();
        labelCity = new javax.swing.JLabel();
        inputCity = new javax.swing.JTextField();
        inputStreet = new javax.swing.JTextField();
        labelStreet = new javax.swing.JLabel();
        labelZipCode = new javax.swing.JLabel();
        labelNumber = new javax.swing.JLabel();
        inputNumber = new javax.swing.JTextField();
        labelState = new javax.swing.JLabel();
        inputComplement = new javax.swing.JTextField();
        inputZipCode = new javax.swing.JFormattedTextField();
        inputState = new javax.swing.JTextField();
        labelComplement = new javax.swing.JLabel();
        labelCountry = new javax.swing.JLabel();
        inputCountry = new javax.swing.JTextField();
        inputLicenseNumber = new javax.swing.JTextField();
        labelLicenseNumber = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Employee");
        setLocation(new java.awt.Point(490, 200));
        setName("frm_CADASTRAR"); // NOI18N

        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelName.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        labelName.setText("* Name:");
        labelName.setName("lbl_NOME"); // NOI18N

        labelSocialSecurityNumber.setText("* SSN:");
        labelSocialSecurityNumber.setName("lbl_CPF"); // NOI18N

        labelRole.setText("* Role:");
        labelRole.setName("lbl_CARGO"); // NOI18N

        inputName.setName("txt_NOME"); // NOI18N

        buttonCreate.setText("Cadastrar");
        buttonCreate.setName("bnt_CADASTRAR"); // NOI18N
        buttonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateActionPerformed(evt);
            }
        });

        comboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operador", "Clínico Geral", "Dermatologia", "Neurologia", "Oftalmologia", "Ortopedia", "Pediatria" }));
        comboRole.setToolTipText("");
        comboRole.setName("cmb_CARGO"); // NOI18N

        try {
            inputSocialSecurityNumber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        inputSocialSecurityNumber.setText("");

        addressPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Address:"));

        labelCity.setText("City:");
        labelCity.setName("lbl_CIDADE"); // NOI18N

        inputCity.setName("txt_CIDADE"); // NOI18N

        inputStreet.setName("txt_BAIRRO"); // NOI18N

        labelStreet.setText("Street");
        labelStreet.setName("lbl_BAIRRO"); // NOI18N

        labelZipCode.setText("Zip Code:");
        labelZipCode.setName("lbl_CEP"); // NOI18N

        labelNumber.setText("Number:");
        labelNumber.setName("lnl_NUM"); // NOI18N

        inputNumber.setName("txt_NUM"); // NOI18N

        labelState.setText("State:");
        labelState.setName("lbl_UF"); // NOI18N

        inputComplement.setName("txt_COMPLEMENTO"); // NOI18N

        try {
            inputZipCode.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        inputZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputZipCodeActionPerformed(evt);
            }
        });

        labelComplement.setText("Complement:");
        labelComplement.setName("lbl_COMPLEMENTO"); // NOI18N

        labelCountry.setText("Country:");
        labelCountry.setName("lbl_UF"); // NOI18N

        javax.swing.GroupLayout addressPanelLayout = new javax.swing.GroupLayout(addressPanel);
        addressPanel.setLayout(addressPanelLayout);
        addressPanelLayout.setHorizontalGroup(
            addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addressPanelLayout.createSequentialGroup()
                        .addComponent(labelZipCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(addressPanelLayout.createSequentialGroup()
                        .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addressPanelLayout.createSequentialGroup()
                                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelStreet)
                                    .addComponent(inputStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNumber)
                                    .addComponent(labelState)))
                            .addGroup(addressPanelLayout.createSequentialGroup()
                                .addComponent(inputCity, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputState, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelCity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputComplement)
                            .addGroup(addressPanelLayout.createSequentialGroup()
                                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelComplement)
                                    .addComponent(labelCountry))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(inputCountry))))
                .addContainerGap())
        );
        addressPanelLayout.setVerticalGroup(
            addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addressPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelCountry)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addressPanelLayout.createSequentialGroup()
                        .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelZipCode)
                            .addComponent(inputZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addressPanelLayout.createSequentialGroup()
                                .addComponent(labelStreet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addressPanelLayout.createSequentialGroup()
                                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelNumber)
                                    .addComponent(labelComplement))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(inputNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputComplement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCity)
                            .addComponent(labelState))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 40, Short.MAX_VALUE))
        );

        labelCity.getAccessibleContext().setAccessibleName("");

        inputLicenseNumber.setName("txt_CRM"); // NOI18N
        inputLicenseNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputLicenseNumberKeyTyped(evt);
            }
        });

        labelLicenseNumber.setText("* License Number:");
        labelLicenseNumber.setName("lbl_CRM"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(comboRole, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputLicenseNumber))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelRole))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelLicenseNumber)
                                            .addComponent(labelSocialSecurityNumber))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE))
                                    .addComponent(inputSocialSecurityNumber)))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelName))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(buttonCreate))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(labelSocialSecurityNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputSocialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRole)
                    .addComponent(labelLicenseNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonCreate))
        );

        labelSocialSecurityNumber.getAccessibleContext().setAccessibleName("");
        comboRole.getAccessibleContext().setAccessibleName("");
        addressPanel.getAccessibleContext().setAccessibleName("Address:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateActionPerformed
     
        try
        {
            /*Funcionario fn = new Funcionario(inputName.getText(), inputSocialSecurityNumber.getText(), inputCity.getText(),
                    inputNumber.getText(), inputState.getText(), cmbUF.getSelectedItem().toString(), inputZipCode.getText(), inputComplement.getText(),
                    String.valueOf(pwfSenha.getPassword()), comboRole.getSelectedItem().toString(), inputLicenseNumber.getText());

            JOptionPane.showMessageDialog(null, fn.insere(inputName.getText(), inputSocialSecurityNumber.getText(), inputCity.getText(),
                    inputNumber.getText(), inputState.getText(), cmbUF.getSelectedItem().toString(), inputZipCode.getText(), inputComplement.getText(),
                    String.valueOf(pwfSenha.getPassword()), comboRole.getSelectedItem().toString(), inputLicenseNumber.getText())); */
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_buttonCreateActionPerformed

    private void inputLicenseNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputLicenseNumberKeyTyped
        
        try
        {
            boolean max = inputLicenseNumber.getText().length() == 10;

            if (max) {
                evt.consume();
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_inputLicenseNumberKeyTyped

    private void inputZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputZipCodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateUpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateUpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateUpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateUpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateUpdateEmployee().setVisible(true);
            }
        });
    }
    
    // FIELDS

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addressPanel;
    private javax.swing.JButton buttonCreate;
    private javax.swing.JComboBox<String> comboRole;
    private javax.swing.JTextField inputCity;
    private javax.swing.JTextField inputComplement;
    private javax.swing.JTextField inputCountry;
    private javax.swing.JTextField inputLicenseNumber;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputNumber;
    private javax.swing.JFormattedTextField inputSocialSecurityNumber;
    private javax.swing.JTextField inputState;
    private javax.swing.JTextField inputStreet;
    private javax.swing.JFormattedTextField inputZipCode;
    private javax.swing.JLabel labelCity;
    private javax.swing.JLabel labelComplement;
    private javax.swing.JLabel labelCountry;
    private javax.swing.JLabel labelLicenseNumber;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelNumber;
    private javax.swing.JLabel labelRole;
    private javax.swing.JLabel labelSocialSecurityNumber;
    private javax.swing.JLabel labelState;
    private javax.swing.JLabel labelStreet;
    private javax.swing.JLabel labelZipCode;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
